doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        dql:
            datetime_functions:
                DAY: DoctrineExtensions\Query\Mysql\Day
                WEEK: DoctrineExtensions\Query\Mysql\Week
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
                NOW: DoctrineExtensions\Query\Mysql\Now
                DAYOFYEAR: DoctrineExtensions\Query\Mysql\DayOfYear
                DAYOFMONTH: DoctrineExtensions\Query\Mysql\DayOfYear
                DATE: DoctrineExtensions\Query\Mysql\Date
                DATE_ADD: DoctrineExtensions\Query\Mysql\DateAdd
                DATEDIFF: DoctrineExtensions\Query\Mysql\DateDiff
                GREATEST: DoctrineExtensions\Query\Mysql\Greatest
                LEAST: DoctrineExtensions\Query\Mysql\Least
                DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                CAST: DoctrineExtensions\Query\Mysql\Cast
                FLOOR: DoctrineExtensions\Query\Mysql\Floor
                DATE_SUB: DoctrineExtensions\Query\Mysql\DateSub
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

